-module(model_test).
-compile({parse_transform,ai_db_orm}).
-sql_module(ai_pgsql_orm).
-table('tb_test').
-field({id,   [{type, integer},{autoincrement, true}]}).
-field({name, [{type, string},{len, 128}]}).
-field({is_paid, [{type,boolean}]}).
-field({is_refund,[{type,boolean}]}).
